const RouteName = {
    CONTACT_SCREEN: 'CONTACT_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    SETTING_SCREEN: 'SETTING_SCREEN',
    TODO_SCREEN: 'TODO_SCREEN',
    FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    SIGNUP_SCREEN: 'SIGNUP_SCREEN',
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    BOTTOM_TAB: 'BOTTOM_TAB',
}

export default RouteName;